 if &shell =~# 'fish$'
    set shell=bash
 endif

 set nocompatible              " be iMproved, required
 filetype off                  " required

 "set termguicolors

call plug#begin('~/.vim/plugged')
 " set the runtime path to include Vundle and initialize
 " set rtp+=~/.config/nvim/bundle/Vundle.vim
 " call vundle#begin()
 " alternatively, pass a path where Vundle should install plugins
 "call vundle#begin('~/some/path/here')

 " let Vundle manage Vundle, required
 " Plugin 'VundleVim/Vundle.vim'

 " -- Leader key -----
 let mapleader="ñ"

 " -- Vimhaviour -----

 " ~ Spaces and tabs ~
 set tabstop=2
 set softtabstop=2
 set shiftwidth=2
 set expandtab
 set shiftround
 set autoindent
 set smartindent

 " ~ Backspace ~
 set backspace=start,eol,indent

 " ~ Buffers ~
 set hidden
 set switchbuf=usetab
 set splitright
 set splitbelow
 set equalalways

 " ~ Backups ~
 set noswapfile
 set nobackup
 set nowritebackup

 " ~ Search ~
 set hlsearch
 set incsearch
 set ignorecase
 set smartcase
 set rtp+=~/.fzf

 " ~ Cursor ~
 let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1


 " ~ Use system clipboard as default buffer
 " ~ Allows yanking between vim/gvim instances
 set clipboard=unnamed

 " ~ Diff ~
 set diffopt+=iwhite

 " ~ Ruby slowness hack ~:w
 let g:ruby_path = system('echo $HOME/.rbenv/shims')

 " ~ Languages ~
 Plug 'vim-ruby/vim-ruby'
 Plug 'plasticboy/vim-markdown'
 Plug 'tpope/vim-rails'
 Plug 'elixir-lang/vim-elixir'
 Plug 'elmcast/elm-vim'


 " ~ Utils ~
 Plug 'scrooloose/nerdtree'
 Plug 'jistr/vim-nerdtree-tabs'
 Plug 'Xuyuanp/nerdtree-git-plugin'
 Plug 'mattn/emmet-vim'
 Plug 'scrooloose/nerdcommenter'
 Plug 'Lokaltog/vim-powerline'
 Plug 'bling/vim-airline'
 Plug 'kien/ctrlp.vim'
 Plug 'tpope/vim-surround'
 Plug 'tpope/vim-repeat'
 Plug 'tpope/vim-unimpaired'
 Plug 'tomtom/quickfixsigns_vim'
 Plug 'tpope/vim-fugitive'
 Plug 'ervandew/supertab'
 Plug 'rking/ag.vim'
 Plug 'vim-syntastic/syntastic'
 Plug 'kana/vim-textobj-user'
 Plug 'kana/vim-textobj-line'
 Plug 'tpope/vim-eunuch'
 Plug 'tpope/vim-abolish'
 Plug 'nelstrom/vim-qargs'
 Plug 'godlygeek/tabular'
 Plug 'tpope/vim-jdaddy'
 Plug 'dag/vim-fish'
 "Plug 'rafi/vim-badge'
 "Plug 'itchyny/vim-gitbranch'
 "Plug 'w0rp/ale'
 "Plug 'git@bitbucket.org:trabe/tb_statusline.vim.git'

 " ~ Themes ~
 "Plug 'badwolf'
 Plug 'morhetz/gruvbox'
 "Plug 'lifepillar/vim-solarized8'
 Plug 'altercation/vim-colors-solarized'
 Plug 'mhartington/oceanic-next'

 Plug 'sjl/vitality.vim'
 Plug 'jceb/vim-orgmode'
 Plug 'tpope/vim-speeddating'

 " ~ Highlighting ~
 Plug 'sheerun/vim-polyglot'
 let g:jsx_ext_required = 0
 let g:javascript_plugin_jsdoc = 1
 let g:javascript_plugin_flow = 1
 Plug 'othree/yajs.vim'
 Plug 'isRuslan/vim-es6'

 " ~ Neoformat ~
 Plug 'sbdchd/neoformat'

" call vundle#end()            " required
 call plug#end()

 filetype plugin indent on    " required

 syntax enable

 " -- GUI customization ----
 set guioptions=

 "set guifont=Inconsolata\ for\ Powerline:h15

 "set guifont=Menlo\ for\ Powerline:h14


 set cul
 set number
 set showmatch

 set laststatus=2
 set showtabline=2
 set scrolloff=3

 set wildmenu
 set wildmode=list:longest

 set wrap
 set whichwrap=b,s,l,h,<,>,~,[,]

 set list
 set listchars -=eol:$
 set listchars +=trail:·
 set listchars +=tab:▸.

 set mouse=a
 set mouse+=a

 set lazyredraw

 set t_Co=256
 set background=dark
 syntax enable

 "colorscheme badwolf
 "colorscheme gruvbox
 colorscheme solarized

 highlight NonText guifg=#333333
 highlight SpecialKey guibg=#555555 guifg=white
 highlight CursorLine guibg=#111111

 " -- Plugin customizations ----
 " ~ Vim-Ruby ~
 imap <s-cr> <cr><cr>end<esc>-cc

 " ~ The NERD tree ~
 let NERDTreeChDirMode=2
 let NERDTreeMouseMode=3
 nnoremap <silent> <leader>p :NERDTreeTabsToggle<cr>

 " ~ Powerline ~
 let g:airline_powerline_fonts = 1
 let g:Powerline_symbols='fancy'

 if !exists('g:airline_symbols')
   let g:airline_symbols = {}
 endif

 if ! has('gui_running')
    set ttimeoutlen=10
    augroup FastEscape
        autocmd!
        au InsertEnter * set timeoutlen=0
        au InsertLeave * set timeoutlen=1000
    augroup END
 endif

 "Setting here the symbols was the only way I found to
 " show the glyphs in the statusline (got at
 " https://github.com/bling/vim-airline/issues/76?source=cc)
 let g:airline_left_sep         = '⮀'
 let g:airline_left_alt_sep     = '⮁'
 let g:airline_right_sep        = '⮂'
 let g:airline_right_alt_sep    = '⮃'
 let g:airline_symbols.branch   = '⭠'
 let g:airline_symbols.readonly = '⭤'
 let g:airline_symbols.liner    = '⭡'

 "let g:tb_statusline_theme = 'solarized_dark'

 "Enabling jsx highlight plugin to works with .js
 let g:jsx_ext_required = 0

 " ~ ctrlp.vim ~
 set wildignore +=*.git
 set wildignore +=*.svn
 set wildignore +=*.class
 set wildignore +=target/**
 set wildignore +=.bundle
 set wildignore +=node_modules/**
 set wildignore +=tmp/**
 let g:ctrlp_custom_ignore = { 'dir': 'tmp\|.sass-cache\|file_repository\|node_modules', 'file': '\.DS_Store' }

 let g:ctrlp_max_height=15
 let g:ctrlp_jump_to_buffer=2
 let g:ctrlp_map = '<leader>f'
 let g:ctrlp_working_path_mode=2

 nmap <silent> <leader>b :CtrlPBuffer<cr>

 " ~ ZoomWin ~
 map <silent> <leader><leader> :ZoomWin<cr>

 " ~ Vim-unimpaired ~
 " Bubble single lines
 nmap <c-up> [e
 nmap <c-down> ]e
 " Bubble multiple lines
 vmap <c-up> [egv
 vmap <c-down> ]egv

 " ~ Fugitive vim ~
 nnoremap <leader>gs :Gstatus<cr>
 nnoremap <leader>gd :Gdiff<cr>
 nnoremap <leader>gc :Gcommit<cr>

 " ~ Syntastic ~
 let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['scss', 'sass'] }
 let g:syntastic_javascript_checkers = ['eslint']

 " ~ Neoformat ~
 let g:neoformat_javascript_prettier = {
  \ 'exe': './node_modules/.bin/prettier',
  \ 'args': ['--write', '--config $(./node_modules/.bin/prettier --find-config-path %:p)'],
  \ 'replace': 1
  \ }

 " ~ Mouse ~
 if &term =~ '^screen'
   " tmux knows the extended mouse mode
    set ttymouse=xterm2
 endif

let g:neoformat_enabled_javascript = ['prettier']

augroup fmt
  autocmd!
  autocmd BufWritePre *.js,*.jsx Neoformat! javascript
augroup end

" NeoFormat
nnoremap <leader><space> :Neoformat<cr>


" -- General Mappings ----

 " ~ Remove searchhighlight ~
 nnoremap <silent> <backspace> :nohlsearch<cr>

 " ~ Easy editting and resourcing of .*vimrc files ~
 nnoremap <leader>ev :tabedit ~/.vimrc<cr>
 nnoremap <leader>sv :source ~/.vimrc<cr>
 nnoremap <leader>egv :tabedit ~/.gvimrc<cr>
 nnoremap <leader>sgv :source ~/.gvimrc<cr>

 " ~ Move between windows ~
 imap <silent> <a-Left> <esc>:wincmd h<cr>
 nmap <silent> <a-Left> :wincmd h<cr>
 nmap <silent> <a-h> :wincmd h<cr>

 imap <silent> <a-Right> <esc>:wincmd l<cr>
 nmap <silent> <a-Right> :wincmd l<cr>
 nmap <silent> <a-l> :wincmd l<cr>

 imap <silent> <a-Up> <esc>:wincmd k<cr>
 nmap <silent> <a-Up> :wincmd k<cr>
 nmap <silent> <a-k> :wincmd k<cr>

 imap <silent> <a-Down> <esc>:wincmd h<cr>
 nmap <silent> <a-Down> :wincmd j<cr>
 nmap <silent> <a-j> :wincmd j<cr>

 "~ Cycle through windows ~
 nnoremap <silent> <tab> :wincmd w<cr>
 nnoremap <silent> <s-tab> :wincmd W<cr>

 " ~ Move between tabs ~
 map <silent> <c-tab> :tabnext<cr>
 imap <silent> <c-tab> <esc>:tabnext<cr>
 map <silent> <c-s-tab> :tabprevious<cr>
 imap <silent> <c-s-tab> <esc>:tabprevious<cr>

 " ~ Goto EOL in insert mode ~
 inoremap <c-e> <esc>A

 " ~ New line ~
 imap <silent> <c-return> <esc>o

 " ~ Selections ~
 " all doc
 nnoremap <leader>a ggVG
 " last edited
 nmap gV `[v`]

 " ~ Fix movements in wrapped lines ~
 noremap j gj
 noremap <down> gj
 noremap k gk
 noremap <up> gk

 " ~ Bubbling ~
 nmap <C-Up> ddkP
 nmap <C-Down> ddp
 vmap <C-Up> xkP`[V`]
 vmap <C-Down> xp`[V`]

 " ~ Fast macro (recorded with qq) ~
 nnoremap <space> @q
 nnoremap <space><space> @@

 " -- Autocommands ----

 " ~ Fix filetypes ~
 autocmd BufRead *.coffe* :set ft=coffee
 autocmd BufRead *.eco* :set ft=eco

 " ~ Help window to the right ~
 augroup Help2Right
  "autocmd!
  "autocmd BufRead $HOME/.vim/*/doc/* :wincmd L
  "autocmd BufRead */vim/*/doc/* :wincmd L
  "autocmd BufRead */snippets/* highlight SpecialKey guibg=#00bb00 guifg=white
 augroup end

 " ~ Close help with q ~
 augroup HelpClose
  "autocmd!
  "autocmd! BufRead */vim/*/doc/* :nmap <buffer> q :q<cr>
  "autocmd! BufRead $HOME/.vim/*/doc/* :nmap <buffer> q :q<cr>
 augroup end

 " Managing Vim config
 nnoremap <leader>ev :e $MYVIMRC<CR>
 nnoremap <leader>sv :source $MYVIMRC<CR>
