require "asou.plugins.colorizer"
require "asou.plugins.compe"
require "asou.plugins.formatter"
require "asou.plugins.hop"
require "asou.plugins.telescope"
require "asou.plugins.treesitter"
require "asou.plugins.trouble"
require "asou.plugins.lualine"
require "asou.plugins.twilight"
-- check require "asou.plugins.shade"
require "asou.plugins.iswap"
require "asou.plugins.lsp_colors"
require "asou.plugins.nvim_tree"
-- check require'asou.plugins.snap'
require "asou.plugins.true_zen"
