require("paq") {
  { 'savq/paq-nvim' },
  { 'AndrewRadev/splitjoin.vim' },
  { 'bronson/vim-trailing-whitespace'},
  { 'ChristianChiarulli/far.vim' },
  { 'cocopon/iceberg.vim'},
  { 'duggiefresh/vim-easydir' },
  { 'folke/lsp-colors.nvim' },
  { 'folke/trouble.nvim' },
  { 'hoob3rt/lualine.nvim' },
  { 'hrsh7th/nvim-compe' },
  { 'kana/vim-textobj-line' },
  { 'kana/vim-textobj-user' },
  { 'mhartington/formatter.nvim' },
  { 'nanotech/jellybeans.vim' },
  { 'neovim/nvim-lspconfig' },
  { 'norcalli/nvim-colorizer.lua' },
  { 'nvim-lua/plenary.nvim' },
  { 'nvim-lua/popup.nvim' },
  { 'nvim-telescope/telescope.nvim' },
  { 'nvim-treesitter/nvim-treesitter', run =':TSUpdate' },
  { 'nvim-treesitter/nvim-treesitter-textobjects' },
  { 'kyazdani42/nvim-web-devicons' },
  { 'kyazdani42/nvim-tree.lua' },
  { 'savq/paq-nvim' },
  { 'tpope/vim-abolish' },
  { 'tpope/vim-commentary' },
  { 'tpope/vim-eunuch' },
  { 'tpope/vim-jdaddy' },
  { 'tpope/vim-repeat' },
  { 'tpope/vim-surround' },
  { 'tpope/vim-unimpaired' },
  { 'wincent/vcs-jump' },
}
